/*CREATE TABLE STUDENT
(
ROLL_NO int(3),
NAME varchar(20),
SUBJECT varchar(20)
);
INSERT INTO STUDENT VALUES(10,'Varun','Cs');
INSERT INTO STUDENT VALUES(16,'Vivek','Maths');
INSERT INTO STUDENT VALUES(19,'Om','PEE');
SELECT * FROM STUDENT
INSERT INTO STUDENT VALUES(13,'Variza','OS');
COMMIT
SELECT * FROM STUDENT
INSERT INTO STUDENT VALUES(22,'Affrojack','EDM');
ROLLBACK*/
SELECT * FROM STUDENT